# Generated by Django 2.0.5 on 2018-06-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfanalyzer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
    ]
