# Generated by Django 2.0.5 on 2018-06-21 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdfanalyzer', '0003_auto_20180621_1647'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
