# Generated by Django 2.0.5 on 2018-06-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfanalyzer', '0004_delete_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(upload_to='textfiles/'),
        ),
    ]
