# Generated by Django 2.0.5 on 2018-06-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfanalyzer', '0005_auto_20180622_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='file_name',
            field=models.CharField(default='foobar', max_length=128),
        ),
    ]
