# Generated by Django 2.0.5 on 2018-06-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfanalyzer', '0007_remove_uploadfile_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='analysed',
            field=models.BooleanField(default=False),
        ),
    ]
