# Generated by Django 2.0.5 on 2018-06-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfanalyzer', '0008_uploadfile_analysed'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='most_common_word',
            field=models.CharField(default='0000', max_length=100),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='word_count',
            field=models.IntegerField(default=-1),
        ),
    ]
