# Generated by Django 2.0.5 on 2018-06-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfanalyzer', '0009_auto_20180622_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='word_count',
            field=models.IntegerField(default=0),
        ),
    ]
