# Generated by Django 2.0.5 on 2018-06-22 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdfanalyzer', '0010_auto_20180622_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='most_common_word',
        ),
        migrations.RemoveField(
            model_name='uploadfile',
            name='word_count',
        ),
    ]
