# Generated by Django 2.0.5 on 2018-06-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfanalyzer', '0011_auto_20180622_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='word_count',
            field=models.IntegerField(default=0),
        ),
    ]
