# Generated by Django 2.0.5 on 2018-06-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfanalyzer', '0012_uploadfile_word_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='word_count',
            field=models.IntegerField(),
        ),
    ]
