# Generated by Django 2.0.5 on 2018-06-22 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdfanalyzer', '0013_auto_20180622_1908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadfile',
            old_name='word_count',
            new_name='wordcount',
        ),
    ]
