# Generated by Django 2.0.5 on 2018-06-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfanalyzer', '0014_auto_20180622_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='wordcount',
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='test',
            field=models.BooleanField(default=False),
        ),
    ]
