# Generated by Django 2.0.5 on 2018-06-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfanalyzer', '0015_auto_20180622_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='test',
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='wordcount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
