# Generated by Django 2.0.5 on 2018-06-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfanalyzer', '0016_auto_20180622_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadfile',
            old_name='wordcount',
            new_name='word_count',
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='most_common_word',
            field=models.CharField(default='0000', max_length=100),
        ),
    ]
