# Generated by Django 2.0.5 on 2018-06-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfanalyzer', '0017_auto_20180622_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='most_common_word',
            field=models.CharField(blank=True, default='0000', max_length=100),
        ),
    ]
