# Generated by Django 2.0.5 on 2018-07-01 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfanalyzer', '0018_auto_20180622_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='session_key',
            field=models.CharField(blank=True, default='0000', max_length=32),
        ),
    ]
