# Generated by Django 2.0.4 on 2018-07-05 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzerequest',
            name='file',
            field=models.FileField(default=False, upload_to=''),
        ),
        migrations.AddField(
            model_name='analyzeresponse',
            name='file',
            field=models.BooleanField(default=False),
        ),
    ]
