# Generated by Django 2.0.7 on 2018-07-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180706_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzerequest',
            name='adjective_count',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='analyzerequest',
            name='most_common_word',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='analyzerequest',
            name='noun_count',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='analyzerequest',
            name='verb_count',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='analyzerequest',
            name='wordcount',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='analyzerequest',
            name='file',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
