# Generated by Django 2.0.7 on 2018-07-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180706_1309'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnalyzeResponse',
        ),
        migrations.RemoveField(
            model_name='analyzerequest',
            name='wordcount',
        ),
        migrations.AddField(
            model_name='analyzerequest',
            name='word_count',
            field=models.BooleanField(default=False, help_text='boolean: auswählen, falls dies Anlayseoption erwüscht.'),
        ),
        migrations.AlterField(
            model_name='analyzerequest',
            name='adjective_count',
            field=models.BooleanField(default=False, help_text='boolean: auswählen, falls dies Anlayseoption erwüscht.'),
        ),
        migrations.AlterField(
            model_name='analyzerequest',
            name='file',
            field=models.FileField(default=None, help_text='file: Datei, die analysiert werden soll.', upload_to=''),
        ),
        migrations.AlterField(
            model_name='analyzerequest',
            name='most_common_word',
            field=models.BooleanField(default=False, help_text='boolean: auswählen, falls dies Anlayseoption erwüscht.'),
        ),
        migrations.AlterField(
            model_name='analyzerequest',
            name='noun_count',
            field=models.BooleanField(default=False, help_text='boolean: auswählen, falls dies Anlayseoption erwüscht.'),
        ),
        migrations.AlterField(
            model_name='analyzerequest',
            name='verb_count',
            field=models.BooleanField(default=False, help_text='boolean: auswählen, falls dies Anlayseoption erwüscht.'),
        ),
    ]
